#version: '3.8'

services:
  backend:
    build: ./backend
    container_name: student-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: student-frontend

  proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
